title: SATRIA SALAM
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: WEB SIF UIN
   url: http://sif.uin-suska.ac.id/

social:
   github: brianmaierjr
   twitter: brianmaierjr
   facebook: brianmaierjr
   email: brimaidesigns@gmail.com

google_analytics: "UA-58263416-1"
